### ISSUE TITLE
Tried any projects connected to Bitcoin?

### ISSUE THREAD

**Issue by noorhashem** [lcarranco/Blockchain_and_IoT#2]
I liked your project and thought you might also be interested in trying out this library for IoT, it integrates bitcoin transactions in HW projects but for Arduino.

Keep up the good work! we need more people tinkering with IoT and Blockchain applications, That was helpful!

https://github.com/elkrem/koyn

there is also a tutorial for a vending machine connected to the bitcoin blockchain.

https://www.hackster.io/elkrem/arduino-based-bitcoin-candy-vending-machine-9f53d8

**Comment by lcarranco** [comment]
Thank you for checking out the project and for the helpful links. Have you completed any of these or similar projects?

**Comment by noorhashem** [comment]
yes, I co-worked with the maker from the link and tried the library. it's working great and you can find a video as well.
If you're interested in knowing any more details or want to replicate it let me know, I'm available.

**Comment by lcarranco** [comment]
Y'all put a lot of work into the project and did an excellent job! Detailed documentation. Keep up the good work!

**Comment by noorhashem** [comment]
Thank you! Keep Tinkering!
